FROM python:3.11-slim

# Установка uv
# RUN pip install uv -i https://pypi.tuna.tsinghua.edu.cn 
# RUN pip install uv
# __сделал так потому что по какой-то замечательной причине не может достучаться до pypi__
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Создание рабочей директории
WORKDIR /app

# Копирование файлов проекта для установки зависимостей
COPY pyproject.toml uv.lock* README.md ./

# Создание виртуального окружения и установка зависимостей через uv sync
RUN uv venv && \
    uv sync

# ARG http_proxy=http://host.docker.internal:12345
# ARG https_proxy=http://host.docker.internal:12345
# client only
# RUN apt-get update && \
#     apt-get install -y docker.io docker-compose-v2 && \
#     rm -rf /var/lib/apt/lists/*
# RUN apt-get update && apt-get install -y \
#     curl \
#     && curl -fsSL https://get.docker.com -o get-docker.sh \
#     && sh get-docker.sh \
#     && rm get-docker.sh \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# RUN apt-get update && apt-get install -y curl \
#     && curl -fL https://get.docker.com -o get-docker.sh \
#     && sh get-docker.sh \
#     && rm get-docker.sh \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*



# RUN apt-get update && apt-get install -y \
#     docker.io \
#     docker-compose-v2 \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    sox \
    libsox-fmt-mp3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Копирование остальных файлов (будет перезаписано volume в dev режиме)
COPY . .
RUN chmod +x deploy/entrypoint.sh

# Команда по умолчанию (переопределяется в docker-compose)
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]