#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_CDR; 
CREATE USER IF NOT EXISTS '${MYSQL_ASTERISK_USER}'@'%' IDENTIFIED BY '${MYSQL_ASTERISK_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_CDR.* TO '${MYSQL_ASTERISK_USER}'@'%';
FLUSH PRIVILEGES;
EOF