"""Стандартные звуки Asterisk (core sounds), доступные без загрузки."""

from __future__ import annotations

BUILTIN_SOUND_NAMES: tuple[str, ...] = (
    "hello-world",
    "demo-congrats",
    "demo-thanks",
    "demo-abouttotry",
    "beep",
    "busy",
    "congestion",
    "pbx-invalid",
    "pbx-transfer",
    "please-hold",
    "auth-thankyou",
    "tt-monkeys",
    "tt-weasels",
    "do-not-disturb",
    "deactivated",
    "vm-intro",
    "vm-goodbye",
    "vm-theperson",
    "vm-youhave",
    "vm-isonphone",
    "vm-nobodyavail",
    "vm-leavemsg",
    "silence/1",
    "feature-not-available",
)

BUILTIN_SOUND_LABELS: dict[str, str] = {
    "hello-world": "hello-world (стандарт)",
    "demo-congrats": "demo-congrats (стандарт)",
    "demo-thanks": "demo-thanks (стандарт)",
    "demo-abouttotry": "demo-abouttotry (стандарт)",
    "beep": "beep (стандарт)",
    "busy": "busy (стандарт)",
    "congestion": "congestion (стандарт)",
    "pbx-invalid": "pbx-invalid (стандарт)",
    "pbx-transfer": "pbx-transfer (стандарт)",
    "please-hold": "please-hold (стандарт)",
    "auth-thankyou": "auth-thankyou (стандарт)",
    "tt-monkeys": "tt-monkeys (стандарт)",
    "tt-weasels": "tt-weasels (стандарт)",
    "do-not-disturb": "do-not-disturb (стандарт)",
    "deactivated": "deactivated (стандарт)",
    "vm-intro": "vm-intro (стандарт)",
    "vm-goodbye": "vm-goodbye (стандарт)",
    "vm-theperson": "vm-theperson (стандарт)",
    "vm-youhave": "vm-youhave (стандарт)",
    "vm-isonphone": "vm-isonphone (стандарт)",
    "vm-nobodyavail": "vm-nobodyavail (стандарт)",
    "vm-leavemsg": "vm-leavemsg (стандарт)",
    "silence/1": "silence/1 (стандарт)",
    "feature-not-available": "feature-not-available (стандарт)",
}
