# Используем легковесный официальный образ Nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d/
COPY ./static /usr/share/nginx/html
# Открываем 80 порт для внешнего доступа
EXPOSE 80
# Запускаем Nginx внутри контейнера
CMD ["nginx", "-g", "daemon off;"]
