FROM nginx:alpine

RUN rm -f /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx-main.conf /etc/nginx/nginx.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./static /usr/share/nginx/html

RUN mkdir -p /etc/nginx/stream.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
