upstream fastapi_backend {
    server fastapi:8000;
    keepalive 32;
}

server {
    listen 80;
    server_name _;

    limit_conn conn_limit 30;

    location = /health_check {
        limit_req zone=api_limit burst=10 nodelay;

        proxy_pass http://fastapi_backend;
        include /etc/nginx/proxy_params;
    }

    location /auth/ {
        limit_req zone=auth_limit burst=5 nodelay;

        proxy_pass http://fastapi_backend;
        include /etc/nginx/proxy_params;
    }

    location / {
        limit_req zone=api_limit burst=60 nodelay;

        proxy_pass http://fastapi_backend;
        include /etc/nginx/proxy_params;
    }
}
