upstream fastapi_backend {
    server fastapi:8000;
    keepalive 32;
}

server {
    listen 80;
    server_name _;

    limit_conn conn_limit 30;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/conf.d/api_locations.inc;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
